Add files via upload
OPSphystech420/WinterGames.PythonProject pull request #2
Opened 2022-11-22 21:45 UTC by OPSphystech420

2022-12-03 10:20 UTC, Andy-Messer requested changes
Исправления минимальны, сделай и получи свой фулл. Молодец, я доволен)

2022-12-03 10:20 UTC, Andy-Messer commented on src/main.py
> +while g.running:
Есть более изящное решение сделать в  Game метод run и убрать это туда

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/PenguinJump/main.py
> +    pygame.mixer.quit()
Добавляй enter в конце файлов(да, душно)

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/PenguinJump/settings.py
> +TITLE = "PenguinJump"
давай сделаем, если  конечно хочешь, json. В него заноси настройки, так будет правильнее

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/constants.py
> +sprites = pygame.sprite.Group()
Почитай что такое [ENUM](https://docs.python.org/3/library/enum.html)

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/draw.py
> +    for p in particles_list:
не надо однобуквенных переменных, даже если очевидно, что они значат. Это плохой тон

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/highscores.py
> +def sort(arr):
а обычный sort чем тебе не подошёл?

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/sprites.py
> +                self.spdx = 0
скупо на слова, что такое spdx? и spdy? производные?)

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/sprites.py
> +        elif self.rect.right > win_res["W"]:
Что такое W? направление? напиши целиком, так читать легче

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/sprites.py
> +        choices = random.choices(img_list, [8, 8, 8, 1, 1, 1, 1, 1], k=10)
8 800 555 35 35 дальше сам, можешь объяснить, что здесь происходит?)

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/SnowRider/data/scripts/sprites.py
> +        self.palette.append(choice.get_at((42, 42)))
[42](https://ru.wikipedia.org/wiki/%D0%9E%D1%82%D0%B2%D0%B5%D1%82_%D0%BD%D0%B0_%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D1%8B%D0%B9_%D0%B2%D0%BE%D0%BF%D1%80%D0%BE%D1%81_%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8,_%D0%B2%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D0%B8_%D0%B2%D1%81%D0%B5%D0%B3%D0%BE_%D1%82%D0%B0%D0%BA%D0%BE%D0%B3%D0%BE)

2022-12-03 10:20 UTC, Andy-Messer commented on src/source/menu.py
> +            self.game.draw_text('Guide', 20, self.game.WEIGHT / 2, self.game.HEIGHT / 7 - 50)
Вот здесь мы и поработаем. Все фразы точно выноси в json и оттуда их забирай, так будет легче ориентироваться в коде, потому что это вермишель

2022-12-06 17:51 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +                self.spdx = 0
скорость игрока по оси x и по оси y

2022-12-06 17:59 UTC, OPSphystech420 commented on src/main.py
> +while g.running:
я переделал

2022-12-06 18:08 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +        choices = random.choices(img_list, [8, 8, 8, 1, 1, 1, 1, 1], k=10)
это веса для каждого изображения в списке,
[8, 8, 8, 1, 1, 1, 1, 1] = 25% вероятность того, что будет выбрано каждое изображение (8/32) * 100 = 25%
Функция возвращает список элементов совокупности размером k, выбранных с заменой.
Если относительные веса или кумулятивные веса не указаны, выбор делается с равной вероятностью.

2022-12-06 18:13 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +        self.palette.append(choice.get_at((42, 42)))
self.palette.append(choice.get_at((32, 32))) Верхний левый
        self.palette.append(choice.get_at((42, 42))) Верхний правый 
        self.palette.append(choice.get_at((32, 48))) Нижний левый

2022-12-07 03:49 UTC, OPSphystech420 commented on src/source/PenguinJump/settings.py
> +TITLE = "PenguinJump"
сделал json, убрал туда настройки, пришлось ознакомится с тем как от туда нормально выгружать, но все получилось

2022-12-07 03:52 UTC, OPSphystech420 commented on src/source/menu.py
> +            self.game.draw_text('Guide', 20, self.game.WEIGHT / 2, self.game.HEIGHT / 7 - 50)
сначала думал проще сделать .txt, но оказалось нифига не удобно, ибо были проблемы с self.blit_screen() и параметрами WEIGHT, HEIGHT. Сделал через json, получилось качественно.

2022-12-07 03:56 UTC, OPSphystech420 commented on src/source/PenguinJump/main.py
> +    pygame.mixer.quit()
не душно, я код стайл соблюдаю, просто файлы так загружаются в гитхаб. Исправил.

2022-12-07 04:02 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +                self.spdx = 0
исправил

2022-12-07 04:02 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +        elif self.rect.right > win_res["W"]:
ширина, высота, исправил

2022-12-07 04:07 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +        choices = random.choices(img_list, [8, 8, 8, 1, 1, 1, 1, 1], k=10)
прокоментировал

2022-12-07 04:07 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/sprites.py
> +        self.palette.append(choice.get_at((42, 42)))
прокоментировал

2022-12-07 04:26 UTC, OPSphystech420 commented on src/source/SnowRider/data/scripts/draw.py
> +    for p in particles_list:
заменил

2024-06-06 17:41 UTC, closed without merging